include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style / formatting
    always_use_package_imports: false
    directives_ordering: false
    sort_constructors_first: false
    sort_pub_dependencies: false
    one_member_abstracts: false

    # Minor style
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_redundant_argument_values: false
    omit_local_variable_types: false
    unnecessary_lambdas: false
    prefer_int_literals: false