name: Flutter CI

on:
  push:
  pull_request:

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.5'
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env
        run: echo "TMDB_API_KEY=" > .env

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test